name: Deploy

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Download Source file
        uses: actions/checkout@v2
        with:
          ref: main

      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: "12.x"

      - name: Build Vuepress
        run: |
          npm i
          npm run docs:build

      - name: copy file via ssh password
        uses: appleboy/scp-action@master
        with:
          host: gocloudcoder.com
          username: root
          password: 6435426Nj!  
          source: docs/.vuepress/dist/*
          target: /www/wwwroot/rdsutbbp.jaronnie.com